FROM jenkins

MAINTAINER Denis Sukhoverkhov "at10tion.angry@yandex.ru"

USER root
RUN apt-get update && apt-get install -qq -y \
    apt-transport-https \
    software-properties-common \
    curl \
    python-software-properties \
    sudo
